import { mkdir, readdir, copyFile, symlink, chmod } from 'node:fs/promises'
import { existsSync, cpSync, statSync, rmSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { execSync } from 'node:child_process'
import { execaCommand, execa } from 'execa'
import os, { homedir } from 'node:os'
import {
  INSTALL_PATH,
  INSTALL_DIR,
  EXPORTS_FILE_PATH,
  XSBUG_LOG_PATH,
  MODDABLE_REPO,
} from '../../setup/constants.js'
import upsert from '../../patching/upsert.js'
import {
  downloadReleaseTools,
  fetchRelease,
  moddableExists,
  MissingReleaseAssetError,
} from '../../setup/moddable.js'
import type { PlatformSetupArgs } from '../../setup/types.js'
import type { Prompter } from '../../../lib/prompter.js'
import type { OperationEvent } from '../../../lib/events.js'
import { isFailure, unwrap } from '../../system/errors.js'
import { which, sourceEnvironment } from '../../system/exec.js'
import type { AdapterContext } from '../interface.js'

export async function* installMac(
  {
    sourceRepo,
    branch,
    release,
  }: PlatformSetupArgs,
  prompter: Prompter,
): AsyncGenerator<OperationEvent, void, undefined> {
  yield { type: 'step:start', message: 'Setting up the mac tools!' }

  const BIN_PATH = resolve(
    INSTALL_PATH,
    'build',
    'bin',
    'mac',
    'release',
  )
  const DEBUG_BIN_PATH = resolve(
    INSTALL_PATH,
    'build',
    'bin',
    'mac',
    'debug',
  )
  const BUILD_DIR = resolve(
    INSTALL_PATH,
    'build',
    'makefiles',
    'mac',
  )

  // 0. ensure xcode command line tools are available
  try {
    await execaCommand('xcode-select -p')
  } catch (error) {
    yield { type: 'step:fail', message: 'Xcode command line tools are required to build the SDK: https://developer.apple.com/xcode/' }
    return
  }

  let buildTools = false

  // 1. clone moddable repo into ./local/share directory if it does not exist yet
  try {
    await mkdir(INSTALL_DIR, { recursive: true })
    await upsert(EXPORTS_FILE_PATH, `# Generated by xs-dev CLI`)
  } catch (error) {
    yield { type: 'step:fail', message: `Error setting up install directory: ${String(error)}` }
    return
  }

  if (existsSync(INSTALL_PATH)) {
    yield { type: 'info', message: 'Moddable repo already installed' }
  } else {
    try {
      if (release !== undefined && (branch === undefined || branch === null)) {
        yield { type: 'step:start', message: 'Getting latest Moddable-OpenSource/moddable release' }
        const remoteReleaseResult = await fetchRelease(release)
        if (isFailure(remoteReleaseResult)) {
          throw new Error(remoteReleaseResult.error)
        }
        const remoteRelease = unwrap(remoteReleaseResult)

        if (remoteRelease.assets.length === 0) {
          yield { type: 'step:done' }
          yield { type: 'warning', message: `Moddable release ${release} does not have any pre-built assets.` }
          buildTools = await prompter.confirm(
            'Would you like to continue setting up and build the SDK locally?',
            true,
          )

          if (!buildTools) {
            yield { type: 'info', message: 'Please select another release version with pre-built assets: https://github.com/Moddable-OpenSource/moddable/releases' }
            return
          }
          yield { type: 'step:start', message: 'Cloning repository' }
        }

        await execa('git', [
          'clone',
          sourceRepo,
          INSTALL_PATH,
          '--depth', '1',
          '--branch', remoteRelease.tag_name,
          '--single-branch',
        ])

        if (!buildTools) {
          await mkdir(BIN_PATH, { recursive: true })
          await mkdir(DEBUG_BIN_PATH, { recursive: true })

          yield { type: 'info', message: 'Downloading release tools' }
          try {
            const universalAssetName = `moddable-tools-macuniversal.zip`
            await downloadReleaseTools({
              writePath: BIN_PATH,
              assetName: universalAssetName,
              release: remoteRelease,
            })
          } catch (error: unknown) {
            if (error instanceof MissingReleaseAssetError) {
              const isArm = os.arch() === 'arm64'
              const assetName = isArm
                ? 'moddable-tools-mac64arm.zip'
                : 'moddable-tools-mac64.zip'
              await downloadReleaseTools({
                writePath: BIN_PATH,
                assetName,
                release: remoteRelease,
              })
            } else {
              throw error as Error
            }
          }
          const tools = await readdir(BIN_PATH)
          await Promise.all(
            tools.map(async (tool) => {
              const src = resolve(BIN_PATH, tool)
              const dst = resolve(DEBUG_BIN_PATH, tool)
              if (tool.endsWith('.app')) {
                const mainPath = resolve(
                  src,
                  'Contents',
                  'MacOS',
                  'main',
                )
                await chmod(mainPath, 0o751)
                execSync(`cp -R ${JSON.stringify(src)} ${JSON.stringify(dst)}`)
              } else {
                await chmod(src, 0o751)
                await copyFile(src, dst)
              }
            }),
          )
        }
      } else if (branch !== undefined && branch !== null) {
        yield { type: 'step:start', message: `Cloning ${sourceRepo} repo` }
        await execa('git', [
          'clone',
          sourceRepo,
          INSTALL_PATH,
          '--depth', '1',
          '--branch', branch,
          '--single-branch',
        ])
        buildTools = true
      } else {
        yield { type: 'step:fail', message: 'Either a release or branch must be specified' }
        return
      }
      yield { type: 'step:done' }
    } catch (error) {
      yield { type: 'step:fail', message: `Error cloning moddable repo: ${String(error)}` }
      return
    }
  }

  // 2. configure MODDABLE env variable, add release binaries dir to PATH
  process.env.MODDABLE = INSTALL_PATH
  process.env.PATH = `${String(process.env.PATH)}:${BIN_PATH}`

  await upsert(EXPORTS_FILE_PATH, `export MODDABLE=${process.env.MODDABLE}`)
  await upsert(EXPORTS_FILE_PATH, `export PATH="${BIN_PATH}:$PATH"`)

  // 3. cd into makefiles dir for platform, run `make`
  if (buildTools) {
    try {
      yield { type: 'step:start', message: 'Building platform tooling' }
      await execaCommand('make', { cwd: BUILD_DIR })
      yield { type: 'step:done' }
    } catch (error) {
      yield { type: 'step:fail', message: `Error building mac tooling: ${String(error)}` }
      return
    }
  }

  // 4. symlink xsbug.app into user applications directory
  try {
    await symlink(
      resolve(BIN_PATH, 'xsbug.app'),
      '/Applications/xsbug.app',
    )
  } catch (error) {
    if (!String(error).includes('exists')) {
      yield { type: 'step:fail', message: `Issue creating symlink for xsbug.app: ${String(error)}` }
      return
    } else {
      yield { type: 'info', message: 'xsbug.app symlink already exists' }
    }
  }

  // 5. install xsbug-log dependencies
  if (which('npm') !== null) {
    yield { type: 'step:start', message: 'Installing xsbug-log dependencies' }
    await execaCommand('npm install', { cwd: XSBUG_LOG_PATH })
    yield { type: 'step:done' }
  }

  yield { type: 'step:done', message: 'Moddable SDK successfully set up! Start a new terminal session and run the "helloworld example": xs-dev run --example helloworld' }
}

export async function* updateMac(
  _ctx: AdapterContext,
  prompter: Prompter,
): AsyncGenerator<OperationEvent, void, undefined> {
  // TODO(Task 7): wire branch/release from command args
  const branch: string | undefined = process.env.XS_DEV_BRANCH
  const release: string | undefined = process.env.XS_DEV_RELEASE

  yield { type: 'info', message: 'Checking for SDK changes' }

  await sourceEnvironment()

  // 0. ensure Moddable exists
  if (!moddableExists()) {
    yield {
      type: 'step:fail',
      message: 'Moddable tooling required. Run `xs-dev setup` before trying again.',
    }
    return
  }

  let rebuildTools = false

  if (release !== undefined && (branch === undefined || branch === null)) {
    try {
      // get tag for current repo
      const currentTagResult = await execaCommand('git tag', {
        cwd: process.env.MODDABLE,
      })
      const currentTag = String(currentTagResult.stdout)

      // get release tag
      const remoteReleaseResult = await fetchRelease(release)
      if (!remoteReleaseResult.success) {
        yield { type: 'step:fail', message: `Failed to fetch release: ${release}` }
        return
      }
      const remoteRelease = remoteReleaseResult.data

      if (typeof currentTag === 'string' && currentTag.trim() === remoteRelease.tag_name) {
        yield { type: 'step:done', message: 'Moddable SDK already up to date!' }
        return
      }

      if (remoteRelease.assets.length === 0) {
        yield {
          type: 'warning',
          message: `Moddable release ${release} does not have any pre-built assets.`,
        }
        rebuildTools = await prompter.confirm(
          'Would you like to continue updating and build the SDK locally?',
          false,
        )

        if (!rebuildTools) {
          yield {
            type: 'info',
            message: 'Please select another release version with pre-built assets: https://github.com/Moddable-OpenSource/moddable/releases',
          }
          return
        }
      }

      yield { type: 'step:start', message: 'Updating Moddable SDK!' }

      // Remove and clone
      try {
        if (process.env.MODDABLE !== undefined) {
          // Use rm -rf for directory removal
          await execa('rm', ['-rf', process.env.MODDABLE])
        }
        await execaCommand(
          `git clone ${MODDABLE_REPO} ${INSTALL_PATH} --depth 1 --branch ${remoteRelease.tag_name} --single-branch`,
        )
      } catch (error) {
        yield { type: 'step:fail', message: `Error cloning repo: ${String(error)}` }
        return
      }

      if (!rebuildTools) {
        try {
          const BIN_PATH = resolve(
            INSTALL_PATH,
            'build',
            'bin',
            'mac',
            'release',
          )
          const DEBUG_BIN_PATH = resolve(
            INSTALL_PATH,
            'build',
            'bin',
            'mac',
            'debug',
          )

          // Create directories
          await mkdir(BIN_PATH, { recursive: true })
          await mkdir(DEBUG_BIN_PATH, { recursive: true })

          try {
            const universalAssetName = `moddable-tools-macuniversal.zip`
            await downloadReleaseTools({
              writePath: BIN_PATH,
              assetName: universalAssetName,
              release: remoteRelease,
            })
          } catch (error: unknown) {
            if (error instanceof MissingReleaseAssetError) {
              const isArm = os.arch() === 'arm64'
              const assetName = isArm
                ? 'moddable-tools-mac64arm.zip'
                : 'moddable-tools-mac64.zip'
              await downloadReleaseTools({
                writePath: BIN_PATH,
                assetName,
                release: remoteRelease,
              })
            } else {
              throw new Error(String(error))
            }
          }

          yield { type: 'info', message: 'Updating tool permissions' }
          const tools = await readdir(BIN_PATH)
          await Promise.all(
            tools.map(async (tool) => {
              if (tool.endsWith('.app')) {
                const mainPath = resolve(
                  BIN_PATH,
                  tool,
                  'Contents',
                  'MacOS',
                  'main',
                )
                await chmod(mainPath, 0o751)
              } else {
                await chmod(resolve(BIN_PATH, tool), 0o751)
              }
              await copyFile(
                resolve(BIN_PATH, tool),
                resolve(DEBUG_BIN_PATH, tool),
              )
            }),
          )

          // Check for npm
          const npmCheck = await execaCommand('which npm', { reject: false })
          if (npmCheck.exitCode === 0) {
            yield { type: 'step:start', message: 'Installing xsbug-log dependencies' }
            await execaCommand('npm install', { cwd: XSBUG_LOG_PATH })
            yield { type: 'step:done' }
          }

          yield {
            type: 'step:done',
            message: 'Moddable SDK successfully updated! Start the xsbug.app and run the "helloworld example": xs-dev run --example helloworld',
          }
        } catch (error) {
          yield {
            type: 'step:fail',
            message: `Error downloading/installing tools: ${String(error)}`,
          }
          return
        }
      }
    } catch (error) {
      yield { type: 'step:fail', message: `Error in release update: ${String(error)}` }
      return
    }
  }

  if (typeof branch === 'string') {
    try {
      const currentRevResult = await execaCommand(`git rev-parse ${branch}`, {
        cwd: process.env.MODDABLE,
      })
      const currentRev = String(currentRevResult.stdout)

      const remoteRevResult = await execaCommand(
        `git ls-remote origin refs/heads/${branch}`,
        { cwd: process.env.MODDABLE },
      )
      const remoteRev = String(remoteRevResult.stdout)

      if (remoteRev.split('\t').shift() === currentRev.trim()) {
        yield { type: 'step:done', message: 'Moddable SDK already up to date!' }
        return
      }

      rebuildTools = true

      yield { type: 'step:start', message: 'Updating Moddable SDK!' }
      yield { type: 'info', message: 'Stashing any unsaved changes before committing' }
      await execaCommand('git stash', { cwd: process.env.MODDABLE, reject: false })
      await execaCommand(`git pull origin ${branch}`, {
        cwd: process.env.MODDABLE,
      })
      yield { type: 'step:done' }
    } catch (error) {
      yield { type: 'step:fail', message: `Error in branch update: ${String(error)}` }
      return
    }
  }

  if (rebuildTools) {
    try {
      const BUILD_DIR = resolve(
        process.env.MODDABLE ?? '',
        'build',
        'bin',
      )
      const TMP_DIR = resolve(
        process.env.MODDABLE ?? '',
        'build',
        'tmp',
      )

      // Remove directories
      await execa('rm', ['-rf', BUILD_DIR], { reject: false })
      await execa('rm', ['-rf', TMP_DIR], { reject: false })

      yield { type: 'step:start', message: 'Rebuilding platform tools' }
      // install release assets or build
      await execaCommand('make', {
        cwd: resolve(
          String(process.env.MODDABLE),
          'build',
          'makefiles',
          'mac',
        ),
        stdio: 'inherit',
      })

      // Check for npm
      const npmCheck = await execaCommand('which npm', { reject: false })
      if (npmCheck.exitCode === 0) {
        yield { type: 'step:start', message: 'Installing xsbug-log dependencies' }
        await execaCommand('npm install', { cwd: XSBUG_LOG_PATH })
        yield { type: 'step:done' }
      }

      yield {
        type: 'step:done',
        message: 'Moddable SDK successfully updated! Start the xsbug.app and run the "helloworld example": xs-dev run --example helloworld',
      }
    } catch (error) {
      yield { type: 'step:fail', message: `Error rebuilding tools: ${String(error)}` }
    }
  }
}

export async function* teardownMac(
  _ctx: AdapterContext,
): AsyncGenerator<OperationEvent, void, undefined> {
  yield { type: 'step:start', message: 'Removing macOS-specific Moddable SDK files' }

  const remove = (path: string): void => {
    rmSync(path, { recursive: true, force: true })
  }

  const NC_PREFS_BACKUP = join(INSTALL_DIR, 'ejectfix', 'com.apple.ncprefs.plist')
  if (existsSync(NC_PREFS_BACKUP) && statSync(NC_PREFS_BACKUP).isFile()) {
    cpSync(
      NC_PREFS_BACKUP,
      join(homedir(), 'Library', 'Preferences', 'com.apple.ncprefs.plist'),
    )
  }
  remove(join(INSTALL_DIR, 'ejectfix'))
  remove('/Applications/xsbug.app')

  yield { type: 'step:done' }
}
