import { mkdir, readdir, copyFile, chmod } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { execSync } from 'node:child_process'
import { execaCommand, execa } from '../system/execa.js'
import os from 'node:os'
import {
  INSTALL_PATH,
  INSTALL_DIR,
  EXPORTS_FILE_PATH,
  XSBUG_LOG_PATH,
} from './constants'
import upsert from '../patching/upsert'
import {
  downloadReleaseTools,
  fetchRelease,
} from './moddable'
import type { PlatformSetupArgs } from './types'
import type { Prompter } from '../../lib/prompter.js'
import type { OperationEvent } from '../../lib/events.js'
import { execWithSudo } from '../system/exec'
import { findMissingDependencies, installPackages } from '../system/packages'
import type { Dependency } from '../system/types'
import { isFailure } from '../system/errors'

function which(bin: string): string | null {
  try {
    const result = execSync(`which ${bin}`, { stdio: 'pipe' }).toString().trim()
    return result.length > 0 ? result : null
  } catch {
    return null
  }
}

export default async function* setupLinux(
  {
    sourceRepo,
    branch,
    release,
  }: PlatformSetupArgs,
  prompter: Prompter,
): AsyncGenerator<OperationEvent> {
  yield { type: 'step:start', message: 'Setting up the Linux tools!' }

  const BIN_PATH = resolve(
    INSTALL_PATH,
    'build',
    'bin',
    'lin',
    'release',
  )
  const DEBUG_BIN_PATH = resolve(
    INSTALL_PATH,
    'build',
    'bin',
    'lin',
    'debug',
  )
  const BUILD_DIR = resolve(
    INSTALL_PATH,
    'build',
    'makefiles',
    'lin',
  )

  let buildTools = false

  // 0. Ensure install directory exists and initialize setup
  try {
    await mkdir(INSTALL_DIR, { recursive: true })
    await upsert(EXPORTS_FILE_PATH, `# Generated by xs-dev CLI`)
  } catch (error) {
    yield { type: 'step:fail', message: `Error setting up install directory: ${String(error)}` }
    return
  }

  // 1. Check for required build tools and libraries
  const dependencies: Dependency[] = [
    { name: 'bison', packageName: 'bison', type: 'binary' },
    { name: 'flex', packageName: 'flex', type: 'binary' },
    { name: 'gcc', packageName: 'gcc', type: 'binary' },
    { name: 'git', packageName: 'git', type: 'binary' },
    { name: 'gperf', packageName: 'gperf', type: 'binary' },
    { name: 'make', packageName: 'make', type: 'binary' },
    { name: 'wget', packageName: 'wget', type: 'binary' },
    { name: 'ncurses', packageName: 'libncurses-dev', type: 'library' },
    { name: 'gtk+-3.0', packageName: 'libgtk-3-dev', type: 'library' },
  ]

  try {
    yield { type: 'step:start', message: 'Checking for missing dependencies' }
    const missingDependenciesResult = await findMissingDependencies(dependencies)
    if (isFailure(missingDependenciesResult)) {
      yield { type: 'step:fail', message: `Error checking dependencies: ${missingDependenciesResult.error}` }
      return
    }

    // 2. Install or update packages required to compile
    if (missingDependenciesResult.data.length !== 0) {
      yield { type: 'step:start', message: 'Attempting to install dependencies' }
      const installResult = await installPackages(missingDependenciesResult.data)
      if (isFailure(installResult)) {
        yield { type: 'step:fail', message: `Error installing dependencies: ${installResult.error}` }
        return
      }
    }
    yield { type: 'step:done' }
  } catch (error) {
    yield { type: 'step:fail', message: `Error during dependency check: ${String(error)}` }
    return
  }

  // 3. Download the Moddable repository or use git to clone
  if (existsSync(INSTALL_PATH)) {
    yield { type: 'info', message: 'Moddable repo already installed' }
  } else {
    try {
      if (release !== undefined && (branch === undefined || branch === null)) {
        yield { type: 'step:start', message: 'Getting latest Moddable-OpenSource/moddable release' }
        const remoteRelease = await fetchRelease(release)
        if (remoteRelease === null) {
          throw new Error(`Failed to fetch release: ${release}`)
        }

        if (remoteRelease.assets.length === 0) {
          yield { type: 'step:done' }
          yield { type: 'warning', message: `Moddable release ${release} does not have any pre-built assets.` }
          buildTools = await prompter.confirm(
            'Would you like to continue setting up and build the SDK locally?',
            true,
          )

          if (!buildTools) {
            yield { type: 'info', message: 'Please select another release version with pre-built assets: https://github.com/Moddable-OpenSource/moddable/releases' }
            return
          }
          yield { type: 'step:start', message: 'Cloning repository' }
        }

        await execa('git', [
          'clone',
          sourceRepo,
          INSTALL_PATH,
          '--depth', '1',
          '--branch', remoteRelease.tag_name,
          '--single-branch',
        ])

        if (!buildTools) {
          await mkdir(BIN_PATH, { recursive: true })
          await mkdir(DEBUG_BIN_PATH, { recursive: true })

          yield { type: 'info', message: 'Downloading release tools' }
          const isArm = os.arch() === 'arm64'
          const assetName = isArm
            ? 'moddable-tools-lin64arm.zip'
            : 'moddable-tools-lin64.zip'
          await downloadReleaseTools({
            writePath: BIN_PATH,
            assetName,
            release: remoteRelease,
          })
          const tools = await readdir(BIN_PATH)
          await Promise.all(
            tools.map(async (tool) => {
              await chmod(resolve(BIN_PATH, tool), 0o751)
              await copyFile(
                resolve(BIN_PATH, tool),
                resolve(DEBUG_BIN_PATH, tool),
              )
            }),
          )
        }
      } else if (branch !== undefined) {
        yield { type: 'step:start', message: `Cloning ${sourceRepo} repo` }
        await execa('git', [
          'clone',
          sourceRepo,
          INSTALL_PATH,
          '--depth', '1',
          '--branch', branch,
          '--single-branch',
        ])
        buildTools = true
      }
      yield { type: 'step:done' }
    } catch (error) {
      yield { type: 'step:fail', message: `Error cloning moddable repo: ${String(error)}` }
      return
    }
  }

  // 4. Setup MODDABLE environment variable and PATH
  process.env.MODDABLE = INSTALL_PATH
  process.env.PATH = `${String(process.env.PATH)}:${BIN_PATH}`

  await upsert(EXPORTS_FILE_PATH, `export MODDABLE=${process.env.MODDABLE}`)
  await upsert(EXPORTS_FILE_PATH, `export PATH="${BIN_PATH}:$PATH"`)

  // 5. Build the Moddable command line tools, simulator, and debugger
  if (buildTools) {
    try {
      yield { type: 'step:start', message: 'Building platform tooling' }
      await execaCommand('make', { cwd: BUILD_DIR })
      yield { type: 'step:done' }
    } catch (error) {
      yield { type: 'step:fail', message: `Error building linux tooling: ${String(error)}` }
      return
    }
  }

  // 6. Install the desktop simulator and xsbug debugger applications
  try {
    yield { type: 'step:start', message: 'Installing simulator' }
    if (release !== undefined && (branch === undefined || branch === null)) {
      await mkdir(
        resolve(
          BUILD_DIR,
          '..',
          '..',
          'tmp',
          'lin',
          'debug',
          'simulator',
        ),
        { recursive: true },
      )
      await execaCommand(
        `mcconfig -m -p x-lin ${resolve(
          INSTALL_PATH,
          'tools',
          'xsbug',
          'manifest.json',
        )}`,
        { cwd: BUILD_DIR },
      )
      await execaCommand(
        `mcconfig -m -p x-lin ${resolve(
          INSTALL_PATH,
          'tools',
          'mcsim',
          'manifest.json',
        )}`,
        { cwd: BUILD_DIR },
      )
    }
    const installResult = await execWithSudo('make install', {
      cwd: BUILD_DIR,
      stdout: process.stdout,
    })
    if (isFailure(installResult)) {
      yield { type: 'step:fail', message: `Error installing simulator: ${installResult.error}` }
      return
    }
    yield { type: 'step:done' }
  } catch (error) {
    yield { type: 'step:fail', message: `Error during simulator installation: ${String(error)}` }
    return
  }

  // 7. Install xsbug-log dependencies if npm is available
  if (which('npm') !== null) {
    try {
      yield { type: 'step:start', message: 'Installing xsbug-log dependencies' }
      await execaCommand('npm install', { cwd: XSBUG_LOG_PATH })
      yield { type: 'step:done' }
    } catch (error) {
      yield { type: 'step:fail', message: `Error installing xsbug-log dependencies: ${String(error)}` }
      return
    }
  }

  yield { type: 'step:done', message: 'Moddable SDK successfully set up! Start a new terminal session and run the "helloworld example": xs-dev run --example helloworld' }
}
