import { describe, it, beforeEach, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { createTempDir, cleanupTempDir } from '../../helpers/runner.js'
import upsert from '#src/toolbox/patching/upsert.js'

describe('upsert', () => {
  let tmpDir: string
  let filePath: string

  beforeEach(async () => {
    tmpDir = await createTempDir()
    filePath = join(tmpDir, 'test.sh')
  })

  afterEach(async () => {
    await cleanupTempDir(tmpDir)
  })

  it('creates the file if it does not exist', async () => {
    await upsert(filePath, 'export FOO=bar')
    const contents = await readFile(filePath, 'utf8')
    assert.ok(contents.includes('export FOO=bar'))
    assert.equal(contents, 'export FOO=bar', 'should not have a leading newline')
  })

  it('appends a new line to an existing file', async () => {
    await upsert(filePath, '# Generated by xs-dev')
    await upsert(filePath, 'export FOO=bar')
    const contents = await readFile(filePath, 'utf8')
    assert.ok(contents.includes('# Generated by xs-dev'))
    assert.ok(contents.includes('export FOO=bar'))
  })

  it('does not duplicate an existing line', async () => {
    await upsert(filePath, 'export FOO=bar')
    await upsert(filePath, 'export FOO=bar')
    const contents = await readFile(filePath, 'utf8')
    assert.equal(contents.split('export FOO=bar').length - 1, 1)
  })
})
